### ISSUE TITLE
Search bar outside screen

### ISSUE THREAD

**Issue by baste00** [jossi87/climbing-web#101]
Search bar goes outside screen on small devices.
![Screenshot_20230821-112426_Chrome](https://github.com/jossi87/climbing-web/assets/42909854/3e145af0-5884-4b40-a62e-7f7c93326584)

**Comment by jossi87** [comment]
Thanks for the reminder 👍 I moved the region-button from left to the right for the search-bar. Everything wraps as it should now.
[screen-capture.webm](https://github.com/jossi87/climbing-web/assets/17472908/4c9c2407-3677-4b5f-b2a8-0f1498101665)
