### ISSUE TITLE
Highlight selected route id label on topo images

### ISSUE THREAD

**Issue by bjorndragland** [jossi87/climbing-web#18]
On busy topo images it can be hard seeing what is the active route/problem. I propose having a border around the number label like shown in the attached image. I've done the changes in my local clone and if this is an interesting additon I can create a fork and create a pull request with this change.
![topo_label_highlight](https://github.com/jossi87/climbing-web/assets/26490838/4542fd85-1d25-4b66-aa62-59cb583a8d73)

**Comment by evancharlton** [comment]
I would love that! (I'm just another user)

**Comment by jossi87** [comment]
Thumbs up from me as well! Looks good 👍

**Comment by jossi87** [comment]
In production now.
