### ISSUE TITLE
Routes with grade 7-/7/7+ renders incorrectly when highlighted in topo

### ISSUE THREAD

**Issue by cklov** [jossi87/climbing-web#2]
Routes with grade 7 renders green instead of yellow when highlighted in topo using edge chromium on windows 10. Seems to be a windows issue as the routes renders correctly in safari on my phone. Also, if I take a screenshot it renders green on my computer, but renders yellow when I open the same screenshot on my phone... 

Attached is a picture of my computer screen taken with my phone

![60d2fe84-b7e2-4ee5-a4fb-8972cb8da0f8](https://github.com/jossi87/climbing-web/assets/45597196/70d66ed7-d7c0-48f0-8c15-f57c507e9fad)

**Comment by jossi87** [comment]
The issue is with the computerscreen, and not the webpage here. Closing issue.
