### ISSUE TITLE
Return HTTP 301/302 for redirects

### ISSUE THREAD

**Issue by evancharlton** [jossi87/climbing-web#23]
Currently, some of the requests have code like this:

```ts
    .then((data) => {
      if (data.redirectUrl && data.redirectUrl != window.location.href) {
        window.location.href = data.redirectUrl;
      }
      return data;
    });
```

This is a bit annoying to deal with - it'd be nice if the payload were _only_ the expected type. I wonder whether it would be possible to return HTTP 301 or HTTP 302 status codes instead?

It would have to be introduced in an opt-in way so that legacy clients continue to work (until everyone is migrated) but it might be worth exploring.

**Comment by jossi87** [comment]
Agree, will fix this in the web service in the next couple of days

**Comment by evancharlton** [comment]
I'll add support to the frontend to support both error codes so that it doesn't need to be a closely-coordinated rollout.

**Comment by evancharlton** [comment]
I'm pretty sure that redirecting a fetch response won't redirect the browser, so adding 301/302 won't help with this. I think the way we're doing it is the way it should be done.
