### ISSUE TITLE
Issue with authentication when signing up with Google

### ISSUE THREAD

**Issue by trondd** [jossi87/climbing-web#27]
Hi! First of all thanks for an amazing project. 

I signed up with Google from Safari on my Mac, and when I navigate round the app, the session is lost. It seems to be consistent when navigating to another sector, but I am no certain. If press "sign in" again I can authenticate again.

I tried the app from Google Chrome, and there I don't have the same issue.

**Comment by jossi87** [comment]
Hi

Thanks for reaching out. I don't have any Apple devices myself, so I can't test this. But I found this: https://community.auth0.com/t/using-auth0-spa-with-brave-safari/65658
Looks like Safari blocks the auth0 cookies. I have implemented the solution mentioned here (using refreshTokens and localstorage).
Can you test it and let me know if this is fixed or needs more research?

**Comment by trondd** [comment]
It is working fine now. Thanks!

**Comment by jossi87** [comment]
Fixed
