### ISSUE TITLE
mistake: Didn't mean to push the branch 'feat/topo-navigation' to the upstream

### ISSUE THREAD

**Issue by bjorndragland** [jossi87/climbing-web#42]
Typed git push out of old habit... It's not meant to be pulled into the repo, it's experimental/ work in progress

**Comment by bjorndragland** [comment]
I guess:

git revert HEAD
git push origin feat/topo-navigation

should 'undo' the push to jossi87/climbing-web ?

**Comment by evancharlton** [comment]
I don't see any branches other than `main` on the upstream (this repo): https://github.com/jossi87/climbing-web/branches/all

I think the branch just lives on your fork: https://github.com/bjorndragland/climbing-web/branches

**Comment by jossi87** [comment]
Nothing on this repo as Evan wrote. But cool that you are experimenting with different things here. Let me/us know if you end up with something that improves the site 👍

**Comment by bjorndragland** [comment]
Ah - cool, I'm a bit of a noobie when it comes to contributing to forked repositories :)
I'm currently experimenting with making the topo images zoomable/pannable on mobile without using the default browser pinch zoom which enlarges everything.
This should help keep the problem name and key functions visible and available while zooming, panning on the svg and switching between problems.
I'm making a new modal for this to be able to test without interfering with existing functionality.
