### ISSUE TITLE
[Feature] provide lat/lng on the /problems endpoint

### ISSUE THREAD

**Issue by evancharlton** [jossi87/climbing-web#72]
**Is your feature request related to a problem? Please describe.**
I'd like to expose other ways to group/filter/render the data on `/problems`, but I'll need the latitude/longitude data (if it exists).

**Describe the solution you'd like**
Provide any existing coordinate data for areas, sectors, and problems

I don't know if it'll bloat the payload too much or anything, but I'd be curious to see!

**Comment by jossi87** [comment]
The endpoint now returns latitude and longitude on area, sector and problem. Most boulders has coordinates, but on routes latitude and longitude on the route is 0. The map should use nearest coordinate on filter in my opinion, so just use the sector coordinates (or area coordinates) if they are 0 on the boulder/route.

Close this feature request if this covers your needs, or let me know if you want something else :)

![image](https://github.com/jossi87/climbing-web/assets/17472908/0e18c502-2ed1-4671-9264-445f00ea726b)

**Comment by evancharlton** [comment]
This is probably good enough. Thanks!

**Comment by evancharlton** [comment]
Could you include the outlines of the areas / sectors, too?

**Comment by jossi87** [comment]
polygonCoords are now included in the AreaSector-object. Area does not have an outline. So the only thing missing in this endpoint now is polyline (approach on sector). Close this issue if you have what you need, or comment again if you want something else 🙂
![image](https://github.com/jossi87/climbing-web/assets/17472908/d2ac8258-1b37-4455-ada4-f5bbc4fdb84d)

**Comment by evancharlton** [comment]
This works great! Thanks!
