### ISSUE TITLE
Extend navbar on large screens

### ISSUE THREAD

**Issue by AlfHou** [jossi87/climbing-web#8]
Currently, the navbar at the top is collapsed. This is convenient on mobile, but doesn't make sense on larger screens.
<img width="1096" alt="Screenshot 2023-06-19 112133" src="https://github.com/jossi87/climbing-web/assets/20001253/bd6ee685-c691-4df6-9f40-73882f0e822a">

**Comment by jossi87** [comment]
I agree. I'm mainly an backend developer, and the site could really need a refresh by someone better on frontend than me. React semantic ui does not come with a responsive menu out of the box. There is also an additional "menu" visible after login (see attached screenshot). I will not focus on this in the near future. But someone else can if they want to :)
![image](https://github.com/jossi87/climbing-web/assets/17472908/21033b0e-f11e-45d6-b6bd-cccb68716c9e)
